LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES:= \
	devmem2.c

LOCAL_CFLAGS += -DGL_GLEXT_PROTOTYPES -DEGL_EGLEXT_PROTOTYPES -UNDEBUG -D_POSIX_SOURCE

LOCAL_MODULE:= devmem2
LOCAL_MODULE_TAGS := optional

LOCAL_SHARED_LIBRARIES := \
	          liblog
include $(BUILD_EXECUTABLE)
